import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className='flex flex-col w-full bg-gradient-to-r from-green-300 via-blue-500 to-purple-600'>
          NextJS template
        </section>
      </main>
    </>
  )
}
